//===========================================================================
//
// - |cff00ff00单元测试地图|r -
//
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Sun Nov 27 05:00:30 2022
//   Map Author: Crainax
//
//===========================================================================
//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************
globals
    // Generated
    rect gg_rct_Wave1 = null
    rect gg_rct_Wave2 = null
    rect gg_rct_Wave3 = null
    rect gg_rct_Wave4 = null
    rect gg_rct_Base = null
    rect gg_rct_BaseBack = null
    rect gg_rct_Home1 = null
    rect gg_rct_Home2 = null
    rect gg_rct_Home3 = null
    rect gg_rct_Home4 = null
    rect gg_rct_Fuben1 = null
    rect gg_rct_Fuben2 = null
    rect gg_rct_Fuben3 = null
    rect gg_rct_Fuben4 = null
    rect gg_rct_Fuben5 = null
    rect gg_rct_Fuben6 = null
    rect gg_rct_Fuben7 = null
    rect gg_rct_Fuben8 = null
    trigger gg_trg_______u = null
    unit gg_unit_hcas_0011 = null
endglobals
function InitGlobals takes nothing returns nothing
endfunction
//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************
//===========================================================================
function CreateBuildingsForPlayer8 takes nothing returns nothing
    local player p = Player(8)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set gg_unit_hcas_0011 = CreateUnit( p, 'hcas', -64.0, -1984.0, 270.000 )
endfunction
//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer8( )
endfunction
//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
endfunction
//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings( )
    call CreatePlayerUnits( )
endfunction
//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************
function CreateRegions takes nothing returns nothing
    local weathereffect we
    set gg_rct_Wave1 = Rect( -5088.0, 3168.0, -4448.0, 3968.0 )
    set gg_rct_Wave2 = Rect( -1568.0, 3360.0, -928.0, 4160.0 )
    set gg_rct_Wave3 = Rect( 1312.0, 3584.0, 1952.0, 4384.0 )
    set gg_rct_Wave4 = Rect( 4320.0, 3232.0, 4960.0, 4032.0 )
    set gg_rct_Base = Rect( -320.0, -2304.0, 192.0, -1664.0 )
    set gg_rct_BaseBack = Rect( -320.0, -3328.0, 160.0, -2848.0 )
    set gg_rct_Home1 = Rect( -10496.0, 1440.0, -8128.0, 3776.0 )
    set gg_rct_Home2 = Rect( 7712.0, 1568.0, 10080.0, 3904.0 )
    set gg_rct_Home3 = Rect( -10464.0, -3680.0, -8096.0, -1344.0 )
    set gg_rct_Home4 = Rect( 7712.0, -3552.0, 10080.0, -1216.0 )
    set gg_rct_Fuben1 = Rect( -11872.0, 7968.0, -8224.0, 11584.0 )
    set gg_rct_Fuben2 = Rect( -5472.0, 8000.0, -1824.0, 11616.0 )
    set gg_rct_Fuben3 = Rect( 1184.0, 8000.0, 4832.0, 11616.0 )
    set gg_rct_Fuben4 = Rect( 7712.0, 7968.0, 11360.0, 11584.0 )
    set gg_rct_Fuben5 = Rect( -11872.0, -11328.0, -8224.0, -7712.0 )
    set gg_rct_Fuben6 = Rect( -5472.0, -11328.0, -1824.0, -7712.0 )
    set gg_rct_Fuben7 = Rect( 1184.0, -11328.0, 4832.0, -7712.0 )
    set gg_rct_Fuben8 = Rect( 7712.0, -11328.0, 11360.0, -7712.0 )
endfunction
//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************
//TESH.scrollpos=0
//TESH.alwaysfold=0
// 当前构建版本
// 当前的平台分包
    // 单元测试
    // lua_print: 单元测试
//这两条是用到YDWE函数就要导入的,没用到就不用导入
// 原生UI的大小
//函数入口
// 用原始地图测试
// 用空地图测试
// 用原始地图测试
//! zinc
/*
* UnitSpell测试文件
* 测试UnitSpell库的所有功能
*
* 测试命令:
* s1 - 测试unitSpell.parse创建和基本属性
* s2 - 测试unitSpell.get获取实例
* s3 - 测试addSpell和getSpell
* s4 - 测试getSpellCount
* s5 - 测试随机创建和删除
* s6 - 测试单位销毁时的清理
*
* -a [unitId] - 创建指定ID的测试单位
* -b [spellId] - 为当前选中单位添加指定技能
*/
library UTUnitSpell requires UnitSpell {
	private unit testUnit = null;
	private unitSpell us = 0;
	private boolean toggle5 = false;
	// 用于Simple技能回调测试的全局变量
	private integer simpleSpellInitCount = 0;
	private integer simpleSpellDestroyCount = 0;
	// 用于回调测试的全局变量
	private integer spellDataInitCount = 0;
	private integer spellDataDestroyCount = 0;
	private integer spellDestroyCount = 0;
	private integer unitDataInitCount = 0; // 添加这个全局变量
private integer destroyCount = 0;
	function Init() {
		// 测试1: parse创建 - 0.1秒
		spellData sd = spellData.byType('AHbz');
		sd = spellData.byType('AHtb');
		sd = spellData.byType('AHtc');
		sd = spellData.byType('AHmt');
		sd = spellData.byType('AHfs');
		UnitTestAutoTimer(0.1, 0, function() {
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			Trace("测试1: unitSpell.parse创建");
			assert.Boolean(us != 0, "单位是否有效");
			assert.Boolean(us.u == testUnit, "绑定单位是否正确");
		}, null);
		// 测试2: get获取 - 0.2秒
		UnitTestAutoTimer(0.2, 0, function() {
			unitSpell us2;
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			us2 = unitSpell.get(testUnit);
			Trace("测试2: unitSpell.get获取");
			assert.Boolean(us == us2, "获取实例是否相同");
		}, null);
		// 测试3: addSpell和getSpell - 0.3秒
		UnitTestAutoTimer(0.3, 0, function() {
			spell sp;
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			sp = spell.entity(testUnit, 'AHbz', 1);
			us.addSpell(sp);
			Trace("测试3: addSpell和getSpell");
			assert.Boolean(us.getSpell(0) == sp, "获取技能是否正确");
		}, null);
		// 测试4: getSpellCount - 0.4秒
		UnitTestAutoTimer(0.4, 0, function() {
			spell sp;
			integer countBefore;
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			sp = spell.entity(testUnit, 'AHbz', 1);
			countBefore = us.getSpellCount();
			us.addSpell(sp);
			Trace("测试4: getSpellCount");
			assert.Boolean(us.getSpellCount() == countBefore + 1, "技能数量是否正确");
		}, null);
		// 测试6: 单位销毁清理 - 0.5秒
		UnitTestAutoTimer(0.5, 0, function() {
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			Trace("测试6: 单位销毁清理");
			assert.Boolean(us.isExist(), "销毁前unitSpell存在");
			RemoveUnit(testUnit);
			assert.Boolean(!us.isExist(), "销毁后unitSpell不存在");
			testUnit = null;
		}, null);
		// 测试7: 技能添加删除测试 - 0.6秒
		UnitTestAutoTimer(0.6, 0, function() {
			integer spellIds[]; // 不同的技能ID
integer i = 0;
			boolean removeResult = false;
			spell invalidSpell = 0;
			spellData sd = 0;
			Trace("开始测试7: 技能添加删除测试");
			spellIds[0] = 'AHbz';
			spellIds[1] = 'AHtb';
			spellIds[2] = 'AHtc';
			spellIds[3] = 'AHmt';
			spellIds[4] = 'AHfs';
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			// 添加5个不同的技能
			for (0 <= i < 5) {
				sd = spellData.byType(spellIds[i]);
				us.addSpellData(sd, 1);
			}
			// 测试技能数量
			assert.Integer(us.getSpellCount(), 5, "添加5个技能后数量是否为5");
			// 测试删除不存在的技能
			removeResult = us.removeSpell(invalidSpell);
			assert.Boolean(!removeResult, "删除不存在的技能应该返回false");
			// 逐个删除技能并检查数量
			for (0 <= i < 5) {
				sd = spellData.byType(spellIds[i]);
				removeResult = us.removeSpellData(sd);
				assert.Boolean(removeResult, "删除第" + I2S(i + 1) + "个技能应该成功");
				assert.Integer(us.getSpellCount(), 4 - i, "删除后技能数量应该为" + I2S(4 - i));
			}
			// 最终检查
			assert.Integer(us.getSpellCount(), 0, "删除所有技能后数量应该为0");
		}, null);
		// 测试8: 重复添加技能测试 - 0.7秒
		UnitTestAutoTimer(0.7, 0, function() {
			spell sp1, sp2;
			spellData sd;
			Trace("开始测试8: 重复添加技能测试");
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			// 测试重复添加相同的spell实例
			sp1 = spell.entity(testUnit, 'AHbz', 1);
			assert.Boolean(us.addSpell(sp1), "首次添加技能实例应该成功");
			assert.Boolean(!us.addSpell(sp1), "重复添加相同技能实例应该失败");
			assert.Integer(us.getSpellCount(), 1, "重复添加后技能数量应该为1");
			// 测试重复添加相同的spellData
			sd = spellData.byType('AHtb');
			assert.Boolean(us.addSpellData(sd, 1), "首次通过spellData添加技能应该成功");
			assert.Boolean(!us.addSpellData(sd, 1), "重复添加相同spellData应该失败");
			assert.Integer(us.getSpellCount(), 2, "重复添加后技能数量应该为2");
		}, null);
		// 测试9: Simple技能测试 - 0.8秒
		UnitTestAutoTimer(0.8, 0, function() {
			spellData sd;
			spellData sds[];
			integer i;
			boolean addResult = false;
			boolean removeResult = false;
			Trace("开始测试9: Simple技能测试");
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			// 创建Simple类型的技能数据
			sd = spellData.new();
			sd.spellType = SPELL_TYPE_SIMPLE;
			sd.maxLevel = 3;
			for (1 <= i <= 3) {
				sds[i] = spellData.new();
				sds[i].spellType = SPELL_TYPE_SIMPLE;
				sds[i].maxLevel = 2+i;
			}
			// 注册初始化和销毁回调
			sd.registerInit(function() {
				simpleSpellInitCount += 1;
				Trace("Simple技能初始化回调被调用, 当前计数: " + I2S(simpleSpellInitCount));
			});
			sd.registerDestroy(function() {
				simpleSpellDestroyCount += 1;
				Trace("Simple技能销毁回调被调用, 当前计数: " + I2S(simpleSpellDestroyCount));
			});
			// 测试添加Simple技能
			addResult = us.addSpellData(sd, 2);
			assert.Boolean(addResult, "添加Simple技能应该成功");
			assert.Integer(us.getSimpleSpellCount(), 1, "Simple技能数量应该为1");
			assert.Integer(simpleSpellInitCount, 1, "Simple技能初始化回调应该被调用一次");
			// 测试获取Simple技能
			assert.Boolean(us.getSimpleSpell(0) == sd, "获取Simple技能应该返回正确的spellData");
			assert.Boolean(us.hasSpellData(sd), "hasSpellData应该能检测到Simple技能");
			// 测试重复添加
			addResult = us.addSpellData(sd, 2);
			assert.Boolean(!addResult, "重复添加Simple技能应该失败");
			assert.Integer(us.getSimpleSpellCount(), 1, "重复添加后Simple技能数量应该仍为1");
			// 测试删除Simple技能
			removeResult = us.removeSpellData(sd);
			assert.Boolean(removeResult, "删除Simple技能应该成功");
			assert.Integer(us.getSimpleSpellCount(), 0, "删除后Simple技能数量应该为0");
			assert.Integer(simpleSpellDestroyCount, 1, "Simple技能销毁回调应该被调用一次");
			// 测试删除不存在的Simple技能
			removeResult = us.removeSpellData(sd);
			assert.Boolean(!removeResult, "删除不存在的Simple技能应该失败");
			// 测试添加多个Simple技能
			for (1 <= i <= 3) {
				addResult = us.addSpellData(sds[i], i);
				assert.Boolean(addResult, "添加第" + I2S(i) + "个Simple技能应该成功");
				assert.Integer(us.getSimpleSpellCount(), i, "添加" + I2S(i) + "个Simple技能后数量应该为" + I2S(i));
			}
			// 测试获取多个Simple技能
			for (1 <= i <= 3) {
				assert.Boolean(us.getSimpleSpell(i-1) == sds[i], "获取第" + I2S(i) + "个Simple技能应该返回正确的spellData");
				assert.Boolean(us.hasSpellData(sds[i]), "hasSpellData应该能检测到第" + I2S(i) + "个Simple技能");
			}
			// 测试逐个删除Simple技能
			for (1 <= i <= 3) {
				removeResult = us.removeSpellData(sds[i]);
				assert.Boolean(removeResult, "删除第" + I2S(i) + "个Simple技能应该成功");
				assert.Integer(us.getSimpleSpellCount(), 3-i, "删除后Simple技能数量应该为" + I2S(3-i));
			}
			// 测试全部删除后再次删除
			for (1 <= i <= 3) {
				removeResult = us.removeSpellData(sds[i]);
				assert.Boolean(!removeResult, "删除已删除的Simple技能应该失败");
			}
		}, null);
		// 测试10: 直接删除单位时的技能清理测试
		UnitTestAutoTimer(0.9, 0, function() {
			spellData sd1, sd2, sd3, sd4, sd5;
			Trace("开始测试10: 直接删除单位时的技能清理测试");
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			destroyCount = 0;
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			// 创建3个Simple技能,回调数不同
			sd1 = spellData.new();
			sd1.spellType = SPELL_TYPE_SIMPLE;
			sd1.maxLevel = 1;
			sd1.registerDestroy(function() {
				destroyCount += 1;
			});
			sd2 = spellData.new();
			sd2.spellType = SPELL_TYPE_SIMPLE;
			sd2.maxLevel = 1;
			sd2.registerDestroy(function() {
				destroyCount += 10;
			});
			sd3 = spellData.new();
			sd3.spellType = SPELL_TYPE_SIMPLE;
			sd3.maxLevel = 1;
			sd3.registerDestroy(function() {
				destroyCount += 100;
			});
			// 创建2个Entity技能
			sd4 = spellData.byType('ACch');
			sd4.spellType = SPELL_TYPE_ENTITY;
			sd4.maxLevel = 1;
			sd4.registerDestroy(function() {
				destroyCount += 1000;
			});
			sd5 = spellData.byType('ACcl');
			sd5.spellType = SPELL_TYPE_ENTITY;
			sd5.maxLevel = 1;
			sd5.registerDestroy(function() {
				destroyCount += 10000;
			});
			// 添加所有技能
			us.addSpellData(sd1, 1); // +1
us.addSpellData(sd2, 1); // +10
us.addSpellData(sd3, 1); // +100
us.addSpellData(sd4, 1); // +1000
us.addSpellData(sd5, 1); // +10000

			// 直接删除单位
			RemoveUnit(testUnit);
			testUnit = null;
			// 验证所有回调都被调用 (1 + 10 + 100 + 1000 + 10000 = 11111)
			assert.Integer(destroyCount, 11111, "删除单位后所有技能的销毁回调应该被正确调用,值应该为11111");
		}, null);
		// 测试11: 技能数量上限测试
		UnitTestAutoTimer(1.0, 0, function() {
			spellData sd;
			integer i;
			boolean addResult;
			Trace("开始测试11: 技能数量上限测试");
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(Player(0), 'hfoo', 0, 0, 0);
			us = unitSpell.parse(testUnit);
			// 尝试添加201个不同的技能
			for (0 <= i < 201) {
				// 每次创建新的spellData
				sd = spellData.new();
				sd.spellType = SPELL_TYPE_SIMPLE;
				sd.maxLevel = 1;
				addResult = us.addSpellData(sd, 1);
				if (i < 200) {
					if (ModuloInteger(i,10) == 0) {
						assert.Boolean(addResult, "添加第" + I2S(IMaxBJ(i-9,0)) +"-" + I2S(i + 1) + "个技能应该成功");
					}
				} else {
					assert.Boolean(!addResult, "添加第201个技能应该失败");
				}
			}
			// 验证最终技能数量
			assert.Integer(us.getSimpleSpellCount(), 200, "最终Simple技能数量应该为200");
		}, null);
		// 测试12: unitData技能初始化测试
		UnitTestAutoTimer(1.1, 0, function() {
			unitData ud;
			spellData sd1, sd2, sd3;
			unit testUnit;
			unitSpell usl;
			// 重置计数
			unitDataInitCount = 0;
			Trace("开始测试12: unitData技能初始化测试");
			// 创建几个不同的spellData
			sd1 = spellData.new();
			sd1.spellType = SPELL_TYPE_SIMPLE;
			sd1.maxLevel = 3;
			sd1.registerInit(function() {
				unitDataInitCount += 1;
				Trace("spellData1初始化回调被调用");
			});
			sd2 = spellData.byType('AHbz');
			sd2.spellType = SPELL_TYPE_ENTITY;
			sd2.maxLevel = 2;
			sd2.registerInit(function() {
				unitDataInitCount += 10;
				Trace("spellData2初始化回调被调用");
			});
			sd3 = spellData.byType('AHtb');
			sd3.spellType = SPELL_TYPE_ENTITY;
			sd3.maxLevel = 4;
			sd3.registerInit(function() {
				unitDataInitCount += 100;
				Trace("spellData3初始化回调被调用");
			});
			// 获取食尸鬼的unitData并添加技能
			ud = unitData.byType('ugho');
			ud.addSpell(sd1, 2); // Simple技能 等级2
ud.addSpell(sd2, 1); // Entity技能 等级1
ud.addSpell(sd3, 3); // Entity技能 等级3

			// 验证unitData中的技能数据是否正确
			assert.Integer(ud.getSpellCount(), 3, "unitData中应该有3个技能");
			assert.Integer(ud.getSpellId(0),sd1, "第1个技能应该是sd1:"+I2S(sd1));
			assert.Integer(ud.getSpellId(1),sd2, "第2个技能应该是sd2:"+I2S(sd2));
			assert.Integer(ud.getSpellId(2),sd3, "第3个技能应该是sd3:"+I2S(sd3));
			assert.Integer(ud.getSpellLevel(0), 2, "sd1的等级应该是2");
			assert.Integer(ud.getSpellLevel(1), 1, "sd2的等级应该是1");
			assert.Integer(ud.getSpellLevel(2), 3, "sd3的等级应该是3");
			// 创建食尸鬼单位并初始化unitSpell
			testUnit = CreateUnit(Player(0), 'ugho', 0, 0, 0);
			usl = unitSpell.parse(testUnit);
			// 验证unitSpell是否正确初始化了所有技能
			assert.Integer(usl.getSimpleSpellCount(), 1, "应该有1个Simple技能");
			assert.Integer(usl.getSpellCount(), 2, "应该有2个Entity技能");
			// 验证Simple技能
			assert.Integer(usl.getSimpleSpell(0) , sd1, "Simple技能应该是sd1:"+I2S(sd1));
			// 验证Entity技能
			assert.Integer(usl.getSpell(0).sd , sd2, "第1个Entity技能应该是sd2:"+I2S(sd2));
			assert.Integer(usl.getSpell(1).sd , sd3, "第2个Entity技能应该是sd3:"+I2S(sd3));
			// 验证所有技能的等级
			assert.Integer(usl.getSimpleSpellLevel(sd1), 2, "Simple技能sd1的等级应该是2");
			assert.Integer(usl.getSpell(0).level, 1, "sd2的等级应该是1");
			assert.Integer(usl.getSpell(1).level, 3, "sd3的等级应该是3");
			// 验证初始化回调是否都被调用 (1 + 10 + 100 = 111)
			assert.Integer(unitDataInitCount, 111, "所有spellData的初始化回调都应该被调用");
			// 清理
			RemoveUnit(testUnit);
			testUnit = null;
		}, null);
	}
	// 测试用例函数保持空实现
	function TTestUTUnitSpell1(player p) {}
	function TTestUTUnitSpell2(player p) {}
	function TTestUTUnitSpell3(player p) {}
	function TTestUTUnitSpell4(player p) {}
	// 只保留测试5的实现，因为它是交互式的随机创建删除测试
	function TTestUTUnitSpell5(player p) {
		integer i;
		integer count;
		unit u;
		group g;
		unitSpell tempUs;
		if (toggle5) {
			// 删除模式：遍历所有单位并删除技能实例
			g = CreateGroup();
			GroupEnumUnitsInRect(g, GetPlayableMapRect(), null);
			ForGroup(g, function() {
				unit u = GetEnumUnit();
				unitSpell tempUs = unitSpell.get(u);
				if (tempUs != 0) {
					tempUs.destroy();
					Trace("删除了单位 " + GetUnitName(u) + " 的技能实例");
				}
				u = null;
			});
			DestroyGroup(g);
			g = null;
			Trace("已清理所有技能实例");
		} else {
			// 创建模式：随机创建10-20个带技能的单位
			count = GetRandomInt(10, 20);
			Trace("准备创建 " + I2S(count) + " 个测试单位");
			for (0 <= i < count) {
				u = CreateUnit(p, 'hfoo',
				GetRandomReal(-1000, 1000),
				GetRandomReal(-1000, 1000),
				GetRandomReal(0, 360));
				tempUs = unitSpell.parse(u);
				if (tempUs != 0) {
					Trace("创建第 " + I2S(i + 1) + " 个单位的技能实例成功");
				}
				u = null;
			}
			Trace("完成创建测试单位");
		}
		toggle5 = !toggle5;
	}
	function TTestUTUnitSpell6(player p) {}
	// 以下测试用例预留
	function TTestUTUnitSpell7(player p) {}
	function TTestUTUnitSpell8(player p) {}
	function TTestUTUnitSpell9(player p) {}
	function TTestUTUnitSpell10(player p) {}
	function TTestUTUnitSpell11(player p) {}
	// 处理带参数的测试命令
	function TTestActUTUnitSpell1(string str) {
		player p;
		integer index;
		integer i;
		integer num;
		integer len;
		string paramS[];
		integer paramI[];
		real paramR[];
		unit selectedUnit;
		p = GetTriggerPlayer();
		index = GetConvertedPlayerId(p);
		num = 0;
		len = StringLength(str);
		// 解析参数
		for (0 <= i <= len - 1) {
			if (SubString(str,i,i+1) == " ") {
				paramS[num] = SubString(str,0,i);
				paramI[num] = S2I(paramS[num]);
				paramR[num] = S2R(paramS[num]);
				num = num + 1;
				str = SubString(str,i + 1,len);
				len = StringLength(str);
				i = -1;
			}
		}
		paramS[num] = str;
		paramI[num] = S2I(paramS[num]);
		paramR[num] = S2R(paramS[num]);
		num = num + 1;
		if (paramS[0] == "a") {
			if (testUnit != null) {
				RemoveUnit(testUnit);
			}
			testUnit = CreateUnit(p, paramI[1], 0, 0, 0);
			us = unitSpell.parse(testUnit);
			Trace("创建测试单位: " + I2S(paramI[1]));
		} else if (paramS[0] == "b") {
			selectedUnit = unitSelect.currentU[index];
			if (selectedUnit != null) {
				us = unitSpell.get(selectedUnit);
				if (us != 0) {
					us.addSpell(spell.entity(selectedUnit, paramI[1], 1));
					Trace("添加技能: " + I2S(paramI[1]));
				}
			}
		}
		p = null;
	}
	function onInit() {
		trigger tr = CreateTrigger();
		TriggerRegisterTimerEventSingle(tr, 0.5);
		TriggerAddCondition(tr, Condition(function() {
			Trace("[UnitSpell] 单元测试已加载");
			Init();
			DestroyTrigger(GetTriggeringTrigger());
		}));
		tr = null;
		UnitTestRegisterChatEvent(function() {
			string str = GetEventPlayerChatString();
			integer i = 1;
			if (SubStringBJ(str,1,1) == "-") {
				TTestActUTUnitSpell1(SubStringBJ(str,2,StringLength(str)));
				return;
			}
			if (str == "s1") TTestUTUnitSpell1(GetTriggerPlayer());
			else if(str == "s2") TTestUTUnitSpell2(GetTriggerPlayer());
			else if(str == "s3") TTestUTUnitSpell3(GetTriggerPlayer());
			else if(str == "s4") TTestUTUnitSpell4(GetTriggerPlayer());
			else if(str == "s5") TTestUTUnitSpell5(GetTriggerPlayer());
			else if(str == "s6") TTestUTUnitSpell6(GetTriggerPlayer());
			else if(str == "s7") TTestUTUnitSpell7(GetTriggerPlayer());
			else if(str == "s8") TTestUTUnitSpell8(GetTriggerPlayer());
			else if(str == "s9") TTestUTUnitSpell9(GetTriggerPlayer());
			else if(str == "s10") TTestUTUnitSpell10(GetTriggerPlayer());
			else if(str == "s11") TTestUTUnitSpell11(GetTriggerPlayer());
		});
		DzUnlockOpCodeLimit(true); // 解锁OpCode限制
}
}
//! endzinc
// lua_print: 空白地图
//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************
//===========================================================================
// Trigger: 简介
//===========================================================================
function Trig_______uActions takes nothing returns nothing
    // 欢迎使用世界编辑器，开始你的地图创造之旅。
    // 你可以从dz.163.com获取最新编辑器咨询。
    // 当你的地图意外损坏时，你可以在backups目录找到你最近26次保存的地图。
    // 任何疑问请加官方作者群：QQ35063417。
    // 本次更新添加判断玩家是否为平台AI玩家，现在平台已经添加虚拟玩家，不用再担心匹配没人问题了！如果你的地图有AI，试试在作者之家开启这个功能吧！
endfunction
//===========================================================================
function InitTrig_______u takes nothing returns nothing
    set gg_trg_______u = CreateTrigger()
    call DoNothing()
    call TriggerAddAction(gg_trg_______u, function Trig_______uActions)
endfunction
//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_______u( )
endfunction
//***************************************************************************
//*
//*  Players
//*
//***************************************************************************
function InitCustomPlayerSlots takes nothing returns nothing
    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )
    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(1), false )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )
    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call ForcePlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(2), false )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )
    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )
    // Player 4
    call SetPlayerStartLocation( Player(4), 4 )
    call ForcePlayerStartLocation( Player(4), 4 )
    call SetPlayerColor( Player(4), ConvertPlayerColor(4) )
    call SetPlayerRacePreference( Player(4), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(4), false )
    call SetPlayerController( Player(4), MAP_CONTROL_COMPUTER )
    // Player 5
    call SetPlayerStartLocation( Player(5), 5 )
    call ForcePlayerStartLocation( Player(5), 5 )
    call SetPlayerColor( Player(5), ConvertPlayerColor(5) )
    call SetPlayerRacePreference( Player(5), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(5), false )
    call SetPlayerController( Player(5), MAP_CONTROL_COMPUTER )
    // Player 6
    call SetPlayerStartLocation( Player(6), 6 )
    call ForcePlayerStartLocation( Player(6), 6 )
    call SetPlayerColor( Player(6), ConvertPlayerColor(6) )
    call SetPlayerRacePreference( Player(6), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(6), false )
    call SetPlayerController( Player(6), MAP_CONTROL_COMPUTER )
    // Player 7
    call SetPlayerStartLocation( Player(7), 7 )
    call ForcePlayerStartLocation( Player(7), 7 )
    call SetPlayerColor( Player(7), ConvertPlayerColor(7) )
    call SetPlayerRacePreference( Player(7), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(7), false )
    call SetPlayerController( Player(7), MAP_CONTROL_COMPUTER )
    // Player 8
    call SetPlayerStartLocation( Player(8), 8 )
    call ForcePlayerStartLocation( Player(8), 8 )
    call SetPlayerColor( Player(8), ConvertPlayerColor(8) )
    call SetPlayerRacePreference( Player(8), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(8), false )
    call SetPlayerController( Player(8), MAP_CONTROL_COMPUTER )
    // Player 9
    call SetPlayerStartLocation( Player(9), 9 )
    call ForcePlayerStartLocation( Player(9), 9 )
    call SetPlayerColor( Player(9), ConvertPlayerColor(9) )
    call SetPlayerRacePreference( Player(9), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(9), false )
    call SetPlayerController( Player(9), MAP_CONTROL_COMPUTER )
    // Player 10
    call SetPlayerStartLocation( Player(10), 10 )
    call ForcePlayerStartLocation( Player(10), 10 )
    call SetPlayerColor( Player(10), ConvertPlayerColor(10) )
    call SetPlayerRacePreference( Player(10), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(10), false )
    call SetPlayerController( Player(10), MAP_CONTROL_COMPUTER )
    // Player 11
    call SetPlayerStartLocation( Player(11), 11 )
    call ForcePlayerStartLocation( Player(11), 11 )
    call SetPlayerColor( Player(11), ConvertPlayerColor(11) )
    call SetPlayerRacePreference( Player(11), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(11), false )
    call SetPlayerController( Player(11), MAP_CONTROL_COMPUTER )
endfunction
function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_013
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerTeam( Player(3), 0 )
    call SetPlayerTeam( Player(4), 0 )
    call SetPlayerTeam( Player(5), 0 )
    call SetPlayerTeam( Player(6), 0 )
    call SetPlayerTeam( Player(7), 0 )
    call SetPlayerTeam( Player(8), 0 )
    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateAllyBJ( Player(6), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(7), Player(8), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(6), true )
    call SetPlayerAllianceStateAllyBJ( Player(8), Player(7), true )
    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(6), true )
    call SetPlayerAllianceStateVisionBJ( Player(8), Player(7), true )
    // Force: TRIGSTR_014
    call SetPlayerTeam( Player(9), 1 )
    call SetPlayerTeam( Player(10), 1 )
    call SetPlayerTeam( Player(11), 1 )
    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(10), true )
    call SetPlayerAllianceStateAllyBJ( Player(9), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(10), Player(11), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(9), true )
    call SetPlayerAllianceStateAllyBJ( Player(11), Player(10), true )
    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(9), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(10), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(11), Player(10), true )
endfunction
function InitAllyPriorities takes nothing returns nothing
    call SetStartLocPrioCount( 0, 3 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrioCount( 1, 3 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrioCount( 2, 3 )
    call SetStartLocPrio( 2, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrioCount( 3, 3 )
    call SetStartLocPrio( 3, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 2, 2, MAP_LOC_PRIO_HIGH )
endfunction
//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************
//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -13568.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -13824.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 13568.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 13312.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -13568.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 13312.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 13568.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -13824.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "NorthrendDay" )
    call SetAmbientNightSound( "NorthrendNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateRegions( )
    call CreateAllUnits( )
    call InitBlizzard( )
    call InitGlobals( )
    call InitCustomTriggers( )
endfunction
//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************
function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_1232" )
    call SetMapDescription( "TRIGSTR_1234" )
    call SetPlayers( 12 )
    call SetTeams( 12 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )
    call DefineStartLocation( 0, 0.0, 0.0 )
    call DefineStartLocation( 1, 0.0, 0.0 )
    call DefineStartLocation( 2, 0.0, 0.0 )
    call DefineStartLocation( 3, 0.0, 0.0 )
    call DefineStartLocation( 4, 0.0, 0.0 )
    call DefineStartLocation( 5, 0.0, 0.0 )
    call DefineStartLocation( 6, 0.0, 0.0 )
    call DefineStartLocation( 7, 0.0, 0.0 )
    call DefineStartLocation( 8, 0.0, 0.0 )
    call DefineStartLocation( 9, 0.0, 0.0 )
    call DefineStartLocation( 10, 0.0, 0.0 )
    call DefineStartLocation( 11, 0.0, 0.0 )
    // Player setup
    call InitCustomPlayerSlots( )
    call InitCustomTeams( )
    call InitAllyPriorities( )
endfunction
/**/
