#ifndef UTDzReviveUnitExploreIncluded
#define UTDzReviveUnitExploreIncluded
#undef OriginMapUnitTestMode
#include "D:/War3/Library/War3Lib/Jass/learn/DzReviveUnitExplore.j"

//! zinc
// Generated by TaskCreateUT.lua; all experiment state stays in this test library.
library UTDzReviveUnitExplore requires DzReviveUnitExplore, Logger {
    private unit subjects[];
    private integer originalId[];
    private integer unitDeaths[];
    private integer playerDeaths[];
    private integer damageEvents[];
    private trigger deathWatch[];
    private trigger damageWatch[];
    private string labels[];
    private real spawnX[];
    private real spawnY[];
    private integer count = 0;
    private integer mode = 0;
    private integer tick = 0;
    private integer round = 0;
    private integer phase = 0;
    private integer runId = 0;
    private integer failures = 0;
    private integer perfDeaths = 0;
    private integer perfCreates = 0;
    private real fpsSum = 0.;
    private integer fpsSamples = 0;
    private integer holdTicks = 1800;
    private integer activeHoldTicks = 1800;
    private real baseX = 0.;
    private real baseY = 0.;
    private player tester = null;
    private unit attacker = null;
    private timer runner = null;
    private boolean savedNeutralAlliance = false;
    private boolean savedTesterAlliance = false;
    private integer savedBounty = 0;
    private integer initialGold = 0;
    private integer initialXP = 0;
    private timer suiteTimer = null;
    private integer suiteStep = 0;

    private function Notice(string message) {
        BJDebugMsg("[DzReviveExplore] " + message);
    }

    private function BoolInt(boolean value) -> integer {
        if (value) { return 1; }
        return 0;
    }

    private function Log(string message) {
        Trace("[DzReviveExplore] run=" + I2S(runId) + " mode=" + I2S(mode) + " tick=" + I2S(tick) + " " + message);
    }
    private function Check(boolean ok, string message) {
        if (!ok) { failures += 1; }
        if (!ok) { assert.Boolean(ok, "[DzReviveExplore] " + message); }
        if (ok) { Log("PASS " + message); }
        else { Log("FAIL " + message); }
    }
    private function Alive(unit u) -> boolean {
        return u != null && GetUnitTypeId(u) != 0 && !IsUnitType(u, UNIT_TYPE_DEAD) && GetWidgetLife(u) > 0.405;
    }
    private function Find(unit u) -> integer {
        integer i;
        for (1 <= i <= count) {
            if (subjects[i] == u) { return i; }
        }
        return 0;
    }
    private function Snapshot(integer i, string stage) {
        unit u = subjects[i];
        Log(stage + " slot=" + I2S(i) + " label=" + labels[i] + " originalHandle=" + I2S(originalId[i]) + " handle=" + I2S(GetHandleId(u)) + " type=" + I2S(GetUnitTypeId(u)));
        if (u != null && GetUnitTypeId(u) != 0) {
            Log("state slot=" + I2S(i) + " alive=" + I2S(BoolInt(Alive(u))) + " hidden=" + I2S(BoolInt(IsUnitHidden(u))) + " paused=" + I2S(BoolInt(IsUnitPaused(u))) + " owner=" + I2S(GetPlayerId(GetOwningPlayer(u))) + " hp=" + R2S(GetWidgetLife(u)) + "/" + R2S(GetUnitState(u, UNIT_STATE_MAX_LIFE)) + " mp=" + R2S(GetUnitState(u, UNIT_STATE_MANA)) + "/" + R2S(GetUnitState(u, UNIT_STATE_MAX_MANA)) + " xy=" + R2S(GetUnitX(u)) + "," + R2S(GetUnitY(u)));
            Log("retained slot=" + I2S(i) + " userData=" + I2S(GetUnitUserData(u)) + " defend=" + I2S(GetUnitAbilityLevel(u, 'Adef')) + " speed=" + R2S(GetUnitMoveSpeed(u)) + " deathUnit=" + I2S(unitDeaths[i]) + " deathPlayer=" + I2S(playerDeaths[i]) + " damage=" + I2S(damageEvents[i]));
            if (mode == 6) {
                Log("spell slot=" + I2S(i) + " berserk=" + I2S(GetUnitAbilityLevel(u, 'Absk')) + " buffBbsk=" + I2S(GetUnitAbilityLevel(u, 'Bbsk')) + " cooldown=" + R2S(DzGetUnitAbilityCool(u, 'Absk')));
            }
        }
        u = null;
    }
    private function OnDeath() {
        integer i = Find(GetTriggerUnit());
        if (i == 0) { return; }
        playerDeaths[i] += 1;
        perfDeaths += 1;
        if (mode != 8 && mode != 9 && (mode != 2 || playerDeaths[i] <= 2 || ModuloInteger(playerDeaths[i], 10) == 0)) {
            Log("DEATH_PLAYER slot=" + I2S(i) + " n=" + I2S(playerDeaths[i]) + " killer=" + I2S(GetHandleId(GetKillingUnit())) + " expectedAttacker=" + I2S(GetHandleId(attacker)));
        }
        // Immediate suspension is intentionally confined to the corresponding controls.
        if (mode == 3) {
            if (i == 3 || i == 4) { UnitSuspendDecay(subjects[i], true); }
            if (i == 2 || i == 4 || i == 5 || i == 6) { ShowUnit(subjects[i], false); }
        }
    }
    private function Cleanup() {
        integer i;
        PauseTimer(runner);
        // Disable callbacks before removing any unit.
        mode = 0;
        for (1 <= i <= count) {
            if (deathWatch[i] != null) { DestroyTrigger(deathWatch[i]); }
            if (damageWatch[i] != null) { DestroyTrigger(damageWatch[i]); }
            deathWatch[i] = null;
            damageWatch[i] = null;
            if (subjects[i] != null && GetUnitTypeId(subjects[i]) != 0) { RemoveUnit(subjects[i]); }
            subjects[i] = null;
        }
        count = 0;
        if (attacker != null) { RemoveUnit(attacker); }
        attacker = null;
        if (tester != null) {
            SetPlayerAlliance(Player(PLAYER_NEUTRAL_AGGRESSIVE), tester, ALLIANCE_PASSIVE, savedNeutralAlliance);
            SetPlayerAlliance(tester, Player(PLAYER_NEUTRAL_AGGRESSIVE), ALLIANCE_PASSIVE, savedTesterAlliance);
            SetPlayerState(Player(PLAYER_NEUTRAL_AGGRESSIVE), PLAYER_STATE_GIVES_BOUNTY, savedBounty);
        }
        tester = null;
    }
    private function NewSubject(integer i, integer rawcode, boolean watch) {
        subjects[i] = CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE), rawcode, spawnX[i], spawnY[i], 270.);
        originalId[i] = GetHandleId(subjects[i]);
        unitDeaths[i] = 0;
        playerDeaths[i] = 0;
        damageEvents[i] = 0;
        if (watch) {
            deathWatch[i] = CreateTrigger();
            TriggerRegisterUnitEvent(deathWatch[i], subjects[i], EVENT_UNIT_DEATH);
            TriggerAddAction(deathWatch[i], function() {
                integer slot = Find(GetTriggerUnit());
                if (slot > 0) {
                    unitDeaths[slot] += 1;
                    if (mode != 2 || unitDeaths[slot] <= 2 || ModuloInteger(unitDeaths[slot], 10) == 0) {
                        Log("DEATH_UNIT slot=" + I2S(slot) + " n=" + I2S(unitDeaths[slot]));
                    }
                }
            });
            damageWatch[i] = CreateTrigger();
            TriggerRegisterUnitEvent(damageWatch[i], subjects[i], EVENT_UNIT_DAMAGED);
            TriggerAddAction(damageWatch[i], function() {
                integer slot = Find(GetTriggerUnit());
                if (slot > 0) {
                    damageEvents[slot] += 1;
                    if (mode != 2 || damageEvents[slot] <= 2 || ModuloInteger(damageEvents[slot], 10) == 0) {
                        Log("DAMAGE slot=" + I2S(slot) + " n=" + I2S(damageEvents[slot]) + " amount=" + R2S(GetEventDamage()) + " source=" + I2S(GetHandleId(GetEventDamageSource())));
                    }
                }
            });
        }
    }
    private function Begin(integer nextMode, player p, integer total) {
        integer i;
        Cleanup();
        runId += 1;
        mode = nextMode;
        tick = 0;
        round = 0;
        phase = 0;
        failures = 0;
        perfDeaths = 0;
        perfCreates = 0;
        fpsSum = 0.;
        fpsSamples = 0;
        activeHoldTicks = holdTicks;
        tester = p;
        savedNeutralAlliance = GetPlayerAlliance(Player(PLAYER_NEUTRAL_AGGRESSIVE), p, ALLIANCE_PASSIVE);
        savedTesterAlliance = GetPlayerAlliance(p, Player(PLAYER_NEUTRAL_AGGRESSIVE), ALLIANCE_PASSIVE);
        savedBounty = GetPlayerState(Player(PLAYER_NEUTRAL_AGGRESSIVE), PLAYER_STATE_GIVES_BOUNTY);
        // Automatic probes must not be contaminated by neutral AI attacking test units.
        SetPlayerAlliance(Player(PLAYER_NEUTRAL_AGGRESSIVE), p, ALLIANCE_PASSIVE, nextMode != 7);
        SetPlayerAlliance(p, Player(PLAYER_NEUTRAL_AGGRESSIVE), ALLIANCE_PASSIVE, nextMode != 7);
        baseX = GetStartLocationX(GetPlayerStartLocation(p));
        baseY = GetStartLocationY(GetPlayerStartLocation(p));
        count = total;
        for (1 <= i <= count) {
            spawnX[i] = baseX + ModuloInteger(i - 1, 10) * 100.;
            spawnY[i] = baseY + 350. + ((i - 1) / 10) * 100.;
            labels[i] = "footman";
        }
        attacker = CreateUnit(p, 'Hpal', baseX, baseY, 90.);
        SetUnitInvulnerable(attacker, true);
        PauseUnit(attacker, true);
        SetPlayerState(Player(PLAYER_NEUTRAL_AGGRESSIVE), PLAYER_STATE_GIVES_BOUNTY, 1);
        initialGold = GetPlayerState(p, PLAYER_STATE_RESOURCE_GOLD);
        initialXP = GetHeroXP(attacker);
        PanCameraToTimedForPlayer(p, baseX, baseY + 350., 0.);
        Log("BEGIN v2 count=" + I2S(count) + " attacker=" + I2S(GetHandleId(attacker)) + " holdSeconds=" + R2S(holdTicks * .1));
        BJDebugMsg("[DzReviveExplore] 开始 s" + I2S(mode) + "，自动测试请等待 END；-stop 可中止。");
    }
    private function Revive(integer i, player owner, real hp, real mp) {
        if (subjects[i] == null || GetUnitTypeId(subjects[i]) == 0) {
            Log("SKIP_REVIVE invalid object slot=" + I2S(i));
            return;
        }
        DzReviveUnit(subjects[i], owner, hp, mp, spawnX[i], spawnY[i]);
    }
    private function Restore(integer i) {
        // Run only AFTER raw post-API observations; these are explicit harness repairs.
        if (Alive(subjects[i])) {
            UnitSuspendDecay(subjects[i], false);
            ShowUnit(subjects[i], true);
            PauseUnit(subjects[i], false);
            SetUnitTimeScale(subjects[i], 1.);
            SetUnitAnimation(subjects[i], "stand");
        }
    }
    private function Finish() {
        PauseTimer(runner);
        Log("END round=" + I2S(round) + " failures=" + I2S(failures) + " (raw engine observations require review)");
        BJDebugMsg("[DzReviveExplore] END s" + I2S(mode) + "，失败断言=" + I2S(failures) + "。请保留原始日志。");
        if (suiteStep > 0) {
            if (failures > 0) {
                suiteStep = 0;
                Notice("整套测试已暂停：本项出现失败，请把日志给我分析，不必继续输入其他指令。");
            } else if (suiteStep == 5) {
                suiteStep = 0;
                Notice("整套基础测试完成！请发送本局日志；性能和删除边界未自动运行。");
            } else {
                suiteStep += 1;
                Notice("2秒后自动开始下一项，请勿操作实验单位。");
                TimerStart(suiteTimer, 2., false, function() {
                    if (suiteStep == 2) { TTestUTDzReviveUnitExplore5(tester); }
                    else if (suiteStep == 3) { TTestUTDzReviveUnitExplore6(tester); }
                    else if (suiteStep == 4) { TTestUTDzReviveUnitExplore2(tester); }
                    else if (suiteStep == 5) { TTestUTDzReviveUnitExplore3(tester); }
                });
            }
        }
    }
    private function ReviveCorpses() {
        integer i;
        PauseTimer(runner);
        phase = 2;
        for (1 <= i <= count) {
            Snapshot(i, "CORPSE_BEFORE");
            if (GetUnitTypeId(subjects[i]) != 0) {
                Revive(i, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.);
                Snapshot(i, "CORPSE_RAW_AFTER_API");
                Check(Alive(subjects[i]), "corpse retained slot=" + I2S(i) + " revives");
                Check(GetHandleId(subjects[i]) == originalId[i], "corpse same handle slot=" + I2S(i));
                Restore(i);
            } else { Log("OBSERVED corpse expired slot=" + I2S(i)); }
        }
        Finish();
    }
    private function BasicStep() {
        if (tick == 20) {
            Notice("s1 [2/5] 杀死步兵；现在是尸体，3秒后调用复活API。");
            KillUnit(subjects[1]);
            Snapshot(1, "BASIC_DEAD");
        } else if (tick == 50) {
            Notice("s1 [3/5] 正在调用 DzReviveUnit……");
            Revive(1, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.);
            Snapshot(1, "RAW_AFTER_API");
            Check(Alive(subjects[1]), "basic revival alive");
            Check(GetHandleId(subjects[1]) == originalId[1], "basic same handle");
            if (!Alive(subjects[1])) {
                Notice("s1 复活后仍为死亡状态。本项停止，保留尸体和日志，先不要运行压力测试。");
                Finish();
                return;
            }
            Restore(1);
            IssuePointOrder(subjects[1], "move", spawnX[1] + 250., spawnY[1]);
            Notice("s1 复活成功，步兵应向右移动；5秒后验证再次死亡。");
        } else if (tick == 100) {
            Check(GetUnitX(subjects[1]) > spawnX[1] + 20., "basic movement after explicit restore");
            Notice("s1 [4/5] 通过伤害再次杀死步兵，检查死亡和受伤监听。");
            UnitDamageTarget(attacker, subjects[1], 100000., false, false, ATTACK_TYPE_CHAOS, DAMAGE_TYPE_UNIVERSAL, WEAPON_TYPE_WHOKNOWS);
            Check(unitDeaths[1] == 2 && playerDeaths[1] == 2, "basic both death listeners fire twice");
            Check(damageEvents[1] > 0, "basic original damage listener fires");
        } else if (tick == 130) {
            Revive(1, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.);
            Snapshot(1, "SECOND_RAW_AFTER_API");
            Check(Alive(subjects[1]), "basic second revival alive");
            Restore(1);
            Notice("s1 [5/5] 流程结束，保留最后的单位供观察。详细结果已写入日志。");
            Finish();
        }
    }
    private function Step() {
        integer i;
        boolean ok;
        tick += 1;
        if (mode == 1) {
            BasicStep();
            return;
        }
        if (mode == 5 || mode == 6) {
            if (mode == 6 && tick == 2) {
                Check(GetUnitAbilityLevel(subjects[1], 'Bbsk') > 0, "fixture berserk buff actually applied");
                Log("fixture setCooldown=" + I2S(BoolInt(DzSetUnitAbilityCool(subjects[1], 'Absk', 20., 30.))));
                PauseUnit(subjects[1], true);
                SetUnitTimeScale(subjects[1], .5);
                Snapshot(1, "CUSTOM_STATE_BEFORE_DEATH");
                KillUnit(subjects[1]);
                Snapshot(1, "CUSTOM_STATE_JUST_DIED");
            }
            if (tick == 10) {
                for (1 <= i <= count) {
                    Snapshot(i, "BEFORE_REVIVE");
                    if (mode == 5) {
                        // Values distinguish absolute points from fractions/percentages.
                        if (i == 1) { Revive(i, tester, 123., 37.); }
                        else { Revive(i, Player(PLAYER_NEUTRAL_AGGRESSIVE), .5, .25); }
                    } else { Revive(i, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.); }
                    Snapshot(i, "RAW_AFTER_API");
                    if (mode != 5 || i == 1) { Check(Alive(subjects[i]), "basic alive slot=" + I2S(i)); }
                    else { Log("PARAM_SMALL_VALUES survival is an observation, not a required contract"); }
                    Check(GetHandleId(subjects[i]) == originalId[i], "same handle slot=" + I2S(i));
                    if (mode == 5 && i == 1) { Check(GetOwningPlayer(subjects[1]) == tester, "owner parameter"); }
                    if (mode == 5 && Alive(subjects[i])) { Check(RAbsBJ(GetUnitX(subjects[i]) - spawnX[i]) < 64. && RAbsBJ(GetUnitY(subjects[i]) - spawnY[i]) < 64., "new position slot=" + I2S(i)); }
                    Restore(i);
                    if (mode != 5) { IssuePointOrder(subjects[i], "move", spawnX[i] + 250., spawnY[i]); }
                }
            }
            if (tick == 30) {
                for (1 <= i <= count) {
                    Snapshot(i, "AFTER_2_SECONDS");
                    if (mode != 5) {
                        Check(GetUnitX(subjects[i]) > spawnX[i] + 20., "moves after revival slot=" + I2S(i));
                        if (Alive(subjects[i])) { UnitDamageTarget(attacker, subjects[i], 100000., false, false, ATTACK_TYPE_CHAOS, DAMAGE_TYPE_UNIVERSAL, WEAPON_TYPE_WHOKNOWS); }
                        Check(unitDeaths[i] == 2 && playerDeaths[i] == 2, "both death listeners fire twice slot=" + I2S(i));
                        Check(damageEvents[i] > 0, "original damage listener still fires slot=" + I2S(i));
                    }
                }
                Finish();
            }
        } else if (mode == 2) {
            if (ModuloInteger(tick, 5) == 0) {
                if (phase == 0) {
                    if (!Alive(subjects[1])) {
                        Check(false, "cycle cannot kill nonliving subject");
                        Finish();
                        return;
                    }
                    UnitDamageTarget(attacker, subjects[1], 100000., false, false, ATTACK_TYPE_CHAOS, DAMAGE_TYPE_UNIVERSAL, WEAPON_TYPE_WHOKNOWS);
                    phase = 1;
                } else {
                    round += 1;
                    Revive(1, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.);
                    ok = Alive(subjects[1]) && GetHandleId(subjects[1]) == originalId[1] && unitDeaths[1] == round && playerDeaths[1] == round && damageEvents[1] >= round;
                    if (!ok || ModuloInteger(round, 10) == 0) {
                        Notice("s2 循环进度：" + I2S(round) + "/100。");
                        Snapshot(1, "CYCLE");
                        Check(ok, "cycle=" + I2S(round) + " alive/handle/death/damage");
                    }
                    Restore(1);
                    phase = 0;
                    if (!ok || round == 100) { Finish(); }
                }
            }
        } else if (mode == 3) {
            if (tick == 1 && GetUnitTypeId(subjects[5]) != 0) { UnitSuspendDecay(subjects[5], true); }
            if (tick == 50 && GetUnitTypeId(subjects[6]) != 0) { UnitSuspendDecay(subjects[6], true); }
            if (ModuloInteger(tick, 300) == 0) {
                Notice("s3 尸体保留观察：" + I2S(tick / 10) + "/" + I2S(activeHoldTicks / 10) + " 秒，尚未复活属于正常等待。");
                for (1 <= i <= count) { Snapshot(i, "CORPSE_POLL"); }
            }
            if (tick >= activeHoldTicks) { ReviveCorpses(); }
        } else if (mode == 8 || mode == 9) {
            // FPS is local telemetry only: never use it to choose synchronized actions.
            fpsSum += I2R(DzGetFPS());
            fpsSamples += 1;
            if (phase == 0) {
                for (1 <= i <= count) { KillUnit(subjects[i]); }
                phase = 1;
            } else {
                round += 1;
                ok = true;
                for (1 <= i <= count) {
                    if (mode == 8) {
                        RemoveUnit(subjects[i]);
                        subjects[i] = null;
                        NewSubject(i, 'hfoo', false);
                        perfCreates += 1;
                    } else {
                        Revive(i, Player(PLAYER_NEUTRAL_AGGRESSIVE), GetUnitState(subjects[i], UNIT_STATE_MAX_LIFE), 0.);
                        if (GetHandleId(subjects[i]) != originalId[i]) { ok = false; }
                    }
                    if (!Alive(subjects[i])) { ok = false; }
                }
                if (perfDeaths != round * count) { ok = false; }
                if (!ok) { Check(false, "perf alive/handle/death count mismatch"); }
                if (ModuloInteger(round, 50) == 0 || !ok) { Log("PERF round=" + I2S(round) + " creates=" + I2S(perfCreates) + " deaths=" + I2S(perfDeaths) + " localMeanFPS=" + R2S(fpsSum / I2R(fpsSamples))); }
                phase = 0;
                if (!ok || round == 300) { Finish(); }
            }
        } else if (mode == 10 && tick == 10) {
            Log("REMOVED_API_CALL_BEGIN savedHandle=" + I2S(originalId[1]) + " (last marker if runtime aborts)");
            DzReviveUnit(subjects[1], tester, 200., 0., spawnX[1], spawnY[1]);
            Log("REMOVED_API_CALL_RETURNED");
            Snapshot(1, "REMOVED_AFTER_API");
            Finish();
        }
    }
    private function StartTimer() { TimerStart(runner, .1, true, function Step); }
    function TTestUTDzReviveUnitExplore1(player p) {
        Begin(1, p, 1);
        NewSubject(1, 'hfoo', true);
        Snapshot(1, "LIVE_BASELINE");
        Notice("s1 [1/5] 已创建步兵。无需操作：2秒后死亡 → 5秒时复活并移动 → 10秒时再次死亡 → 13秒时复活并结束。");
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore2(player p) {
        Begin(2, p, 1);
        NewSubject(1, 'hfoo', true);
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore3(player p) {
        integer i;
        Begin(3, p, 6);
        labels[1] = "untreated";
        labels[2] = "hide-only";
        labels[3] = "suspend-at-death-only";
        labels[4] = "hide+suspend-at-death";
        labels[5] = "hide+suspend-at-0.1s";
        labels[6] = "hide+suspend-at-5s";
        for (1 <= i <= count) {
            NewSubject(i, 'hfoo', true);
            KillUnit(subjects[i]);
            Snapshot(i, "CORPSE_START");
        }
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore4(player p) {
        if (mode == 3 && phase != 2) { ReviveCorpses(); }
        else { Log("s4 requires s3; it revives current corpse controls early"); }
    }
    function TTestUTDzReviveUnitExplore5(player p) {
        integer i;
        Begin(5, p, 2);
        for (1 <= i <= count) {
            NewSubject(i, 'hmpr', true);
            Snapshot(i, "PARAM_BASELINE");
            KillUnit(subjects[i]);
            spawnX[i] += 600.;
        }
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore6(player p) {
        Begin(6, p, 1);
        NewSubject(1, 'hfoo', true);
        SetUnitUserData(subjects[1], 24680);
        UnitAddAbility(subjects[1], 'Adef');
        UnitAddAbility(subjects[1], 'Absk');
        SetUnitMoveSpeed(subjects[1], 150.);
        Log("fixture berserkOrder=" + I2S(BoolInt(IssueImmediateOrder(subjects[1], "berserk"))));
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore7(player p) {
        Begin(7, p, 1);
        NewSubject(1, 'hfoo', true);
        PauseUnit(attacker, false);
        Log("MANUAL: select paladin, attack footman; after death use -revive; -kill/-damage/-status supported");
        Snapshot(1, "MANUAL_START");
    }
    function TTestUTDzReviveUnitExplore8(player p) {
        integer i;
        Begin(8, p, 100);
        for (1 <= i <= count) { NewSubject(i, 'hfoo', false); }
        perfCreates = count;
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore9(player p) {
        integer i;
        Begin(9, p, 100);
        for (1 <= i <= count) { NewSubject(i, 'hfoo', false); }
        perfCreates = count;
        StartTimer();
    }
    function TTestUTDzReviveUnitExplore10(player p) {
        Begin(10, p, 1);
        NewSubject(1, 'hfoo', true);
        KillUnit(subjects[1]);
        Log("REMOVE_BEGIN savedHandle=" + I2S(originalId[1]));
        RemoveUnit(subjects[1]);
        Log("REMOVE_DONE; intentionally retaining variable for isolated invalid-object experiment");
        StartTimer();
    }
    private function Help() {
        Notice("v2 已加载。输入 s1 看13秒完整演示；输入 -all 自动执行基础整套（约5分钟，失败即停）；-stop 中止，-status 记录状态。");
    }
    function TTestActUTDzReviveUnitExplore1(string str) {
        integer i;
        integer seconds;
        if (str == "all") {
            PauseTimer(suiteTimer);
            suiteStep = 1;
            Notice("开始整套：s1 → s5 → s6 → s2 → s3。无需继续输入，出现失败会自动停止。");
            TTestUTDzReviveUnitExplore1(GetTriggerPlayer());
        } else if (str == "help") { Help(); }
        else if (str == "stop") {
            suiteStep = 0;
            PauseTimer(suiteTimer);
            Log("STOP requested");
            Cleanup();
        } else if (str == "status") {
            for (1 <= i <= count) { Snapshot(i, "MANUAL_STATUS"); }
            if (attacker != null) { Log("REWARDS gold=" + I2S(GetPlayerState(tester, PLAYER_STATE_RESOURCE_GOLD)) + " goldDelta=" + I2S(GetPlayerState(tester, PLAYER_STATE_RESOURCE_GOLD) - initialGold) + " heroXP=" + I2S(GetHeroXP(attacker)) + " xpDelta=" + I2S(GetHeroXP(attacker) - initialXP)); }
        } else if (SubString(str, 0, 5) == "hold ") {
            seconds = S2I(SubString(str, 5, StringLength(str)));
            if (seconds >= 10 && seconds <= 900) {
                holdTicks = seconds * 10;
                Log("holdSeconds=" + I2S(seconds));
            } else { Log("hold accepts 10..900 seconds"); }
        } else if (mode == 7) {
            if (str == "kill" && Alive(subjects[1])) { KillUnit(subjects[1]); }
            else if (str == "damage" && Alive(subjects[1])) { UnitDamageTarget(attacker, subjects[1], 100000., false, false, ATTACK_TYPE_CHAOS, DAMAGE_TYPE_UNIVERSAL, WEAPON_TYPE_WHOKNOWS); }
            else if (str == "revive" && !Alive(subjects[1])) {
                Snapshot(1, "MANUAL_BEFORE_REVIVE");
                Revive(1, Player(PLAYER_NEUTRAL_AGGRESSIVE), 200., 0.);
                Snapshot(1, "MANUAL_RAW_AFTER_API");
                Log("Raw result retained. Use -restore if visibility/pause/animation needs explicit repair.");
            } else if (str == "restore") { Restore(1); }
        }
    }
    function onInit() {
        integer i;
        trigger tr = CreateTrigger();
        runner = CreateTimer();
        suiteTimer = CreateTimer();
        for (0 <= i < bj_MAX_PLAYER_SLOTS) { TriggerRegisterPlayerUnitEvent(tr, Player(i), EVENT_PLAYER_UNIT_DEATH, null); }
        TriggerAddAction(tr, function OnDeath);
        tr = null;
        UnitTestAutoTimer(.5, 1., function() { Help(); }, null);
        UnitTestRegisterChatEvent(function() {
            string str = GetEventPlayerChatString();
            player p = GetTriggerPlayer();
            if (SubString(str, 0, 1) == "s") {
                suiteStep = 0;
                PauseTimer(suiteTimer);
            }
            if (SubString(str, 0, 1) == "-") { TTestActUTDzReviveUnitExplore1(SubString(str, 1, StringLength(str))); }
            else if (str == "s1") { TTestUTDzReviveUnitExplore1(p); }
            else if (str == "s2") { TTestUTDzReviveUnitExplore2(p); }
            else if (str == "s3") { TTestUTDzReviveUnitExplore3(p); }
            else if (str == "s4") { TTestUTDzReviveUnitExplore4(p); }
            else if (str == "s5") { TTestUTDzReviveUnitExplore5(p); }
            else if (str == "s6") { TTestUTDzReviveUnitExplore6(p); }
            else if (str == "s7") { TTestUTDzReviveUnitExplore7(p); }
            else if (str == "s8") { TTestUTDzReviveUnitExplore8(p); }
            else if (str == "s9") { TTestUTDzReviveUnitExplore9(p); }
            else if (str == "s10") { TTestUTDzReviveUnitExplore10(p); }
            p = null;
        });
    }
}
//! endzinc
#endif
