local lfs = require "lfs"
local fu = require "Lua.utils.FileUtils"
local ini = require "Lua.utils.Ini"
local path = require "Lua.path"

local localDzApi = {}

local DEFAULT_MODES = {
    VERSION_ALPHA = true,
    VERSION_BETA = true,
    VERSION_UNITTEST = true
}

local function ensureDir(dir)
    if lfs.attributes(dir, "mode") == "directory" then
        return true
    end
    local parent = dir:match("(.+)/[^/]+$")
    if parent and lfs.attributes(parent, "mode") ~= "directory" then
        local ok, err = ensureDir(parent)
        if not ok then
            return false, err
        end
    end
    local ok, err = lfs.mkdir(dir)
    if ok or lfs.attributes(dir, "mode") == "directory" then
        return true
    end
    return false, err
end

local function readCurrentVersion()
    local content = fu.GetContent(path.rewave) or ""
    return content:match("#define%s+CURRENT_BUILD_VERSION%s+(VERSION_%w+)") or "VERSION_UNITTEST"
end

local function splitModes(value)
    if not value or value == "" then
        return DEFAULT_MODES
    end

    local modes = {}
    for item in tostring(value):gmatch("[^,%s]+") do
        modes[item] = true
    end
    return modes
end

local function boolEnabled(value)
    if value == nil or value == "" then
        return true
    end
    value = tostring(value):lower()
    return value == "1" or value == "true" or value == "yes" or value == "on"
end

local function jassString(value)
    value = tostring(value or "")
    value = value:gsub("\\", "\\\\")
    value = value:gsub('"', '\\"')
    return '"' .. value .. '"'
end

local function emptyHeader(version)
    return table.concat({
        "#ifndef WAR3LIB_LOCAL_DZAPI_MOCK_GENERATED_H",
        "#define WAR3LIB_LOCAL_DZAPI_MOCK_GENERATED_H",
        "// Generated by War3Lib compile flow. Current build: " .. version,
        "#endif"
    }, "\n") .. "\n"
end

local function buildHeader(version, cfg)
    local localSection = cfg["War3Lib.LocalDzApi"] or {}
    local dzSection = cfg["DzAPI"] or {}
    local startTime = localSection["DzAPI_Map_GetGameStartTime"] or dzSection["DzAPI_Map_GetGameStartTime"] or "0"

    startTime = tostring(startTime):match("^%-?%d+$") and tostring(startTime) or "0"

    local lines = {
        "#ifndef WAR3LIB_LOCAL_DZAPI_MOCK_GENERATED_H",
        "#define WAR3LIB_LOCAL_DZAPI_MOCK_GENERATED_H",
        "// Generated by War3Lib compile flow. Source: " .. (path.localDzApiIni or ""),
        "",
        "#if defined(WAR3LIB_SECOND_WAVE)",
        "#define DzAPI_Map_GetGameStartTime() " .. startTime,
        "#endif",
        "",
        "#endif"
    }

    return table.concat(lines, "\n") .. "\n"
end

local function readMockState()
    local version = readCurrentVersion()
    local cfg = ini.read(path.localDzApiIni)
    local localSection = cfg["War3Lib.LocalDzApi"] or {}
    local modes = splitModes(localSection["Modes"])
    local enabled = boolEnabled(localSection["Enable"]) and modes[version] == true
    return version, cfg, localSection, enabled
end

function localDzApi.generate()
    local version, cfg, _, enabled = readMockState()
    local content

    if enabled then
        content = buildHeader(version, cfg)
        print("[DzAPI本地替换]启用: " .. version .. " <- " .. path.localDzApiIni)
    else
        content = emptyHeader(version)
        print("[DzAPI本地替换]跳过: " .. version)
    end

    local ok, err = ensureDir(path.generatedConfig)
    if not ok then
        return false, err
    end
    return fu.WriteOver(path.localDzApiMockH, content)
end

function localDzApi.applyMapConfigReplacement(filePath)
    local version, cfg, localSection, enabled = readMockState()
    if not enabled then
        print("[DzAPI本地替换]MapConfig跳过: " .. version)
        return true
    end

    local content = fu.GetContent(filePath)
    if not content then
        return false, "无法读取MapConfig替换目标: " .. tostring(filePath)
    end

    local mapConfig = cfg["War3Lib.LocalDzApi.MapConfig"] or {}
    local defaultValue = localSection["MapConfigDefault"] or ""
    local keyCount = 0
    local fallbackCount = 0

    content = content:gsub('DzAPI_Map_GetMapConfig%s*%(%s*"([^"]*)"%s*%)', function(key)
        keyCount = keyCount + 1
        return jassString(mapConfig[key] or defaultValue)
    end)

    content = content:gsub('DzAPI_Map_GetMapConfig%s*(%b())', function()
        fallbackCount = fallbackCount + 1
        return jassString(defaultValue)
    end)

    local ok, err = fu.WriteOver(filePath, content)
    if ok then
        print(string.format("[DzAPI本地替换]MapConfig完成: 按Key替换=%d, 兜底替换=%d", keyCount, fallbackCount))
    end
    return ok, err
end

return localDzApi
